import Head from 'next/head'
import LandingPage from '../components/LandingPage'
import About from '../components/About'
import Footer from '../components/Footer'
import Projects from '../components/Projects'
import CustomCursor from '../components/CustomCursor'
import ClientOnly from '../components/ClientOnly'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Dennis Baksheev - Software Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png" />
      </Head>
      <main className='full-page' id='content'>
        <LandingPage />
        <About />
        <Projects />
      </main>
      <div orientation="right" className="email-container">
        <div className="email-display">
          <a href="mailto:dennisbaksheev1@gmail.com">dennisbaksheev1@gmail.com</a>
        </div>
      </div>
      <Footer />
      <ClientOnly>
        <CustomCursor />
      </ClientOnly>
    </div>
  )
}
